### PR TITLE
Theme agnostic logos

### PR DESCRIPTION
**Pull request by ZenithRogue**
## Issue
Current Strata branding is currently limited to explicit light or dark theme definitions.  This prevents usage of the logos on pages that are not capable of dynamically changing images based on the theme.

#### Example from the StrataSource org readme:
image

## Resolution
The pull request adds theme-agnostic logos for all relevant logos, under the `agnostic` header.  This includes `color` and `mono` variants.
#### Examples of theme-agnostic logo applied:
| Light Theme | Dark Theme |
| -- | -- |
| image | image |

## Considerations
SVG theming is not possible for HTML embedded `` images, as the browser interprets it as an image directly, and does not respect `@media` CSS tags.

### CODE REVIEW

**Comment by JJL772** [comment]
Thanks for the PR!

@LauraWebdev Could you take a look at this?

**Comment by tsa96** [comment]
Gray is never going to look good with this logo.

According to Laura (in internal Discord) you can use 
```md
![Fancy logo](./dark.png#gh-dark-mode-only)
![Fancy logo](./light.png#gh-light-mode-only)
```
on Github specifically. On other sites, they can either use the SVG (which has a `prefers-color-scheme` @media query), or it's the responsibility of the website author to switch between the right variant.

If you're up for updating the README.md to use the above markdown that'd be much apprecated :)

**Review by LauraWebdev — CHANGES_REQUESTED** [review]
Hey there, yeah I think introducing a third color into our branding (one that is also barely readable on light backgrounds, it fails 3 out of 4 WCAG contrast checks) is probably not the way we should take.

The option with using the github theme id's is my prefered solution, for our own pages, we can utilize CSS to do the same.

**Comment by ZenithRogue** [comment]
> one that is also barely readable on light backgrounds

the color chosen was `#808080`, which is exactly halfway between black and white, not sure how this is barely readable ¯\\\_(ツ)\_/¯

> If you're up for updating the README.md to use the above markdown that'd be much apprecated

i can do that

**Comment by ZenithRogue** [comment]
Just checked in a gist, the proposed gh dark/light assignment does not work
```md
![Fancy logo](./dark.png#gh-dark-mode-only)
![Fancy logo](./light.png#gh-light-mode-only)
```
https://gist.github.com/ZenithRogue/ecf065f0dc998def67c6628ed0327aa7
image

**Comment by ZenithRogue** [comment]
looks like we can directly define it in the readme like this though:
```html
<p align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://branding.stratasource.org/i/strata/logo/ondark/color.svg">
    <img width=512 src="https://branding.stratasource.org/i/strata/logo/onlight/color.svg">
  </picture>
</p>
```
<p align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://branding.stratasource.org/i/strata/logo/ondark/color.svg">
    
  </picture>
</p>

**Comment by ZenithRogue** [comment]
closing in favor of https://github.com/StrataSource/.github/pull/1

**Pull request closed without merging**
